import {Posts} from "@/components/Posts";
import {PostSearch} from "@/components/PostSearch";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog | Next App",
  description: "Generated by create next app",
};

export default async function Blog() {
  return (
    <>
      <h5 className='text-center text-2xl font-bold p-4'>Blog Page</h5>
      <PostSearch/>
      <Posts />
    </>
  );
}
