import "./globals.css";
import type { Metadata } from "next";
import Footer from "@/components/footer";
import Header from "@/components/header";


export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=''>
        <Header />
        <main className="mx-auto max-w-[1200px] h-[calc(100%-112px)] bg-[#cecece]">
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
